/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'transportation' : IDL.Null,
  'diet' : IDL.Null,
  'homeEnergy' : IDL.Null,
  'shopping' : IDL.Null,
});
export const FootprintInput = IDL.Record({
  'value' : IDL.Float64,
  'unit' : IDL.Text,
  'category' : Category,
});
export const FootprintEstimate = IDL.Record({
  'moneySavedPerYear' : IDL.Float64,
  'category' : Category,
  'co2KgPerYear' : IDL.Float64,
});
export const ChallengeId = IDL.Nat;
export const ChallengeStatus = IDL.Variant({
  'active' : IDL.Null,
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
});
export const Challenge = IDL.Record({
  'id' : ChallengeId,
  'durationDays' : IDL.Nat,
  'status' : ChallengeStatus,
  'title' : IDL.Text,
  'co2ReductionKg' : IDL.Float64,
  'description' : IDL.Text,
  'participantCount' : IDL.Nat,
  'category' : IDL.Text,
});
export const ConversionFactor = IDL.Record({
  'unit' : IDL.Text,
  'moneySavedPerUnit' : IDL.Float64,
  'category' : Category,
  'co2KgPerUnit' : IDL.Float64,
});
export const UserProgress = IDL.Record({
  'daysCompleted' : IDL.Nat,
  'challengeId' : ChallengeId,
  'lastCheckIn' : IDL.Opt(IDL.Nat),
  'currentStreak' : IDL.Nat,
});
export const OffsetOptionId = IDL.Nat;
export const OffsetCategory = IDL.Variant({
  'treePlanting' : IDL.Null,
  'oceanCleanup' : IDL.Null,
  'communitySolar' : IDL.Null,
  'wildlifeConservation' : IDL.Null,
});
export const OffsetOption = IDL.Record({
  'id' : OffsetOptionId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : OffsetCategory,
  'iconUrl' : IDL.Text,
  'co2OffsetKg' : IDL.Float64,
  'costUsd' : IDL.Float64,
});
export const OffsetPurchase = IDL.Record({
  'totalCo2OffsetKg' : IDL.Float64,
  'optionId' : OffsetOptionId,
  'purchasedAt' : IDL.Nat,
  'totalCostUsd' : IDL.Float64,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'calculateFootprint' : IDL.Func(
      [IDL.Vec(FootprintInput)],
      [IDL.Vec(FootprintEstimate)],
      ['query'],
    ),
  'calculateTotals' : IDL.Func(
      [IDL.Vec(FootprintEstimate)],
      [IDL.Record({ 'totalSavings' : IDL.Float64, 'totalCo2' : IDL.Float64 })],
      ['query'],
    ),
  'getChallenge' : IDL.Func([ChallengeId], [IDL.Opt(Challenge)], ['query']),
  'getChallengesByStatus' : IDL.Func(
      [ChallengeStatus],
      [IDL.Vec(Challenge)],
      ['query'],
    ),
  'getConversionFactors' : IDL.Func([], [IDL.Vec(ConversionFactor)], ['query']),
  'getDefaultProgress' : IDL.Func([ChallengeId], [UserProgress], ['query']),
  'getOffsetOption' : IDL.Func(
      [OffsetOptionId],
      [IDL.Opt(OffsetOption)],
      ['query'],
    ),
  'getOffsetOptionsByCategory' : IDL.Func(
      [OffsetCategory],
      [IDL.Vec(OffsetOption)],
      ['query'],
    ),
  'listChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
  'listOffsetOptions' : IDL.Func([], [IDL.Vec(OffsetOption)], ['query']),
  'simulatePurchase' : IDL.Func(
      [OffsetOptionId, IDL.Nat],
      [IDL.Opt(OffsetPurchase)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'transportation' : IDL.Null,
    'diet' : IDL.Null,
    'homeEnergy' : IDL.Null,
    'shopping' : IDL.Null,
  });
  const FootprintInput = IDL.Record({
    'value' : IDL.Float64,
    'unit' : IDL.Text,
    'category' : Category,
  });
  const FootprintEstimate = IDL.Record({
    'moneySavedPerYear' : IDL.Float64,
    'category' : Category,
    'co2KgPerYear' : IDL.Float64,
  });
  const ChallengeId = IDL.Nat;
  const ChallengeStatus = IDL.Variant({
    'active' : IDL.Null,
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Challenge = IDL.Record({
    'id' : ChallengeId,
    'durationDays' : IDL.Nat,
    'status' : ChallengeStatus,
    'title' : IDL.Text,
    'co2ReductionKg' : IDL.Float64,
    'description' : IDL.Text,
    'participantCount' : IDL.Nat,
    'category' : IDL.Text,
  });
  const ConversionFactor = IDL.Record({
    'unit' : IDL.Text,
    'moneySavedPerUnit' : IDL.Float64,
    'category' : Category,
    'co2KgPerUnit' : IDL.Float64,
  });
  const UserProgress = IDL.Record({
    'daysCompleted' : IDL.Nat,
    'challengeId' : ChallengeId,
    'lastCheckIn' : IDL.Opt(IDL.Nat),
    'currentStreak' : IDL.Nat,
  });
  const OffsetOptionId = IDL.Nat;
  const OffsetCategory = IDL.Variant({
    'treePlanting' : IDL.Null,
    'oceanCleanup' : IDL.Null,
    'communitySolar' : IDL.Null,
    'wildlifeConservation' : IDL.Null,
  });
  const OffsetOption = IDL.Record({
    'id' : OffsetOptionId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : OffsetCategory,
    'iconUrl' : IDL.Text,
    'co2OffsetKg' : IDL.Float64,
    'costUsd' : IDL.Float64,
  });
  const OffsetPurchase = IDL.Record({
    'totalCo2OffsetKg' : IDL.Float64,
    'optionId' : OffsetOptionId,
    'purchasedAt' : IDL.Nat,
    'totalCostUsd' : IDL.Float64,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'calculateFootprint' : IDL.Func(
        [IDL.Vec(FootprintInput)],
        [IDL.Vec(FootprintEstimate)],
        ['query'],
      ),
    'calculateTotals' : IDL.Func(
        [IDL.Vec(FootprintEstimate)],
        [
          IDL.Record({
            'totalSavings' : IDL.Float64,
            'totalCo2' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getChallenge' : IDL.Func([ChallengeId], [IDL.Opt(Challenge)], ['query']),
    'getChallengesByStatus' : IDL.Func(
        [ChallengeStatus],
        [IDL.Vec(Challenge)],
        ['query'],
      ),
    'getConversionFactors' : IDL.Func(
        [],
        [IDL.Vec(ConversionFactor)],
        ['query'],
      ),
    'getDefaultProgress' : IDL.Func([ChallengeId], [UserProgress], ['query']),
    'getOffsetOption' : IDL.Func(
        [OffsetOptionId],
        [IDL.Opt(OffsetOption)],
        ['query'],
      ),
    'getOffsetOptionsByCategory' : IDL.Func(
        [OffsetCategory],
        [IDL.Vec(OffsetOption)],
        ['query'],
      ),
    'listChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
    'listOffsetOptions' : IDL.Func([], [IDL.Vec(OffsetOption)], ['query']),
    'simulatePurchase' : IDL.Func(
        [OffsetOptionId, IDL.Nat],
        [IDL.Opt(OffsetPurchase)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };