/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'transportation' : null } |
  { 'diet' : null } |
  { 'homeEnergy' : null } |
  { 'shopping' : null };
export interface Challenge {
  'id' : ChallengeId,
  'durationDays' : bigint,
  'status' : ChallengeStatus,
  'title' : string,
  'co2ReductionKg' : number,
  'description' : string,
  'participantCount' : bigint,
  'category' : string,
}
export type ChallengeId = bigint;
export type ChallengeStatus = { 'active' : null } |
  { 'upcoming' : null } |
  { 'completed' : null };
export interface ConversionFactor {
  'unit' : string,
  'moneySavedPerUnit' : number,
  'category' : Category,
  'co2KgPerUnit' : number,
}
export interface FootprintEstimate {
  'moneySavedPerYear' : number,
  'category' : Category,
  'co2KgPerYear' : number,
}
export interface FootprintInput {
  'value' : number,
  'unit' : string,
  'category' : Category,
}
export type OffsetCategory = { 'treePlanting' : null } |
  { 'oceanCleanup' : null } |
  { 'communitySolar' : null } |
  { 'wildlifeConservation' : null };
export interface OffsetOption {
  'id' : OffsetOptionId,
  'name' : string,
  'description' : string,
  'category' : OffsetCategory,
  'iconUrl' : string,
  'co2OffsetKg' : number,
  'costUsd' : number,
}
export type OffsetOptionId = bigint;
export interface OffsetPurchase {
  'totalCo2OffsetKg' : number,
  'optionId' : OffsetOptionId,
  'purchasedAt' : bigint,
  'totalCostUsd' : number,
  'quantity' : bigint,
}
export interface UserProgress {
  'daysCompleted' : bigint,
  'challengeId' : ChallengeId,
  'lastCheckIn' : [] | [bigint],
  'currentStreak' : bigint,
}
export interface _SERVICE {
  'calculateFootprint' : ActorMethod<
    [Array<FootprintInput>],
    Array<FootprintEstimate>
  >,
  'calculateTotals' : ActorMethod<
    [Array<FootprintEstimate>],
    { 'totalSavings' : number, 'totalCo2' : number }
  >,
  'getChallenge' : ActorMethod<[ChallengeId], [] | [Challenge]>,
  'getChallengesByStatus' : ActorMethod<[ChallengeStatus], Array<Challenge>>,
  'getConversionFactors' : ActorMethod<[], Array<ConversionFactor>>,
  'getDefaultProgress' : ActorMethod<[ChallengeId], UserProgress>,
  'getOffsetOption' : ActorMethod<[OffsetOptionId], [] | [OffsetOption]>,
  'getOffsetOptionsByCategory' : ActorMethod<
    [OffsetCategory],
    Array<OffsetOption>
  >,
  'listChallenges' : ActorMethod<[], Array<Challenge>>,
  'listOffsetOptions' : ActorMethod<[], Array<OffsetOption>>,
  'simulatePurchase' : ActorMethod<
    [OffsetOptionId, bigint],
    [] | [OffsetPurchase]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];