/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FootprintEstimate {
    moneySavedPerYear: number;
    category: Category;
    co2KgPerYear: number;
}
export type OffsetOptionId = bigint;
export interface FootprintInput {
    value: number;
    unit: string;
    category: Category;
}
export interface OffsetPurchase {
    totalCo2OffsetKg: number;
    optionId: OffsetOptionId;
    purchasedAt: bigint;
    totalCostUsd: number;
    quantity: bigint;
}
export interface OffsetOption {
    id: OffsetOptionId;
    name: string;
    description: string;
    category: OffsetCategory;
    iconUrl: string;
    co2OffsetKg: number;
    costUsd: number;
}
export type ChallengeId = bigint;
export interface ConversionFactor {
    unit: string;
    moneySavedPerUnit: number;
    category: Category;
    co2KgPerUnit: number;
}
export interface UserProgress {
    daysCompleted: bigint;
    challengeId: ChallengeId;
    lastCheckIn?: bigint;
    currentStreak: bigint;
}
export interface Challenge {
    id: ChallengeId;
    durationDays: bigint;
    status: ChallengeStatus;
    title: string;
    co2ReductionKg: number;
    description: string;
    participantCount: bigint;
    category: string;
}
export enum Category {
    transportation = "transportation",
    diet = "diet",
    homeEnergy = "homeEnergy",
    shopping = "shopping"
}
export enum ChallengeStatus {
    active = "active",
    upcoming = "upcoming",
    completed = "completed"
}
export enum OffsetCategory {
    treePlanting = "treePlanting",
    oceanCleanup = "oceanCleanup",
    communitySolar = "communitySolar",
    wildlifeConservation = "wildlifeConservation"
}
export interface backendInterface {
    calculateFootprint(inputs: Array<FootprintInput>): Promise<Array<FootprintEstimate>>;
    calculateTotals(estimates: Array<FootprintEstimate>): Promise<{
        totalSavings: number;
        totalCo2: number;
    }>;
    getChallenge(id: ChallengeId): Promise<Challenge | null>;
    getChallengesByStatus(status: ChallengeStatus): Promise<Array<Challenge>>;
    getConversionFactors(): Promise<Array<ConversionFactor>>;
    getDefaultProgress(challengeId: ChallengeId): Promise<UserProgress>;
    getOffsetOption(id: OffsetOptionId): Promise<OffsetOption | null>;
    getOffsetOptionsByCategory(category: OffsetCategory): Promise<Array<OffsetOption>>;
    listChallenges(): Promise<Array<Challenge>>;
    listOffsetOptions(): Promise<Array<OffsetOption>>;
    simulatePurchase(optionId: OffsetOptionId, quantity: bigint): Promise<OffsetPurchase | null>;
}
import type { Category as _Category, Challenge as _Challenge, ChallengeId as _ChallengeId, ChallengeStatus as _ChallengeStatus, ConversionFactor as _ConversionFactor, FootprintEstimate as _FootprintEstimate, FootprintInput as _FootprintInput, OffsetCategory as _OffsetCategory, OffsetOption as _OffsetOption, OffsetOptionId as _OffsetOptionId, OffsetPurchase as _OffsetPurchase, UserProgress as _UserProgress } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateFootprint(arg0: Array<FootprintInput>): Promise<Array<FootprintEstimate>> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateFootprint(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateFootprint(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async calculateTotals(arg0: Array<FootprintEstimate>): Promise<{
        totalSavings: number;
        totalCo2: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTotals(to_candid_vec_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTotals(to_candid_vec_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getChallenge(arg0: ChallengeId): Promise<Challenge | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallenge(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallenge(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChallengesByStatus(arg0: ChallengeStatus): Promise<Array<Challenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallengesByStatus(to_candid_ChallengeStatus_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallengesByStatus(to_candid_ChallengeStatus_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversionFactors(): Promise<Array<ConversionFactor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversionFactors();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversionFactors();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDefaultProgress(arg0: ChallengeId): Promise<UserProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultProgress(arg0);
                return from_candid_UserProgress_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultProgress(arg0);
            return from_candid_UserProgress_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOffsetOption(arg0: OffsetOptionId): Promise<OffsetOption | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOffsetOption(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOffsetOption(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOffsetOptionsByCategory(arg0: OffsetCategory): Promise<Array<OffsetOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOffsetOptionsByCategory(to_candid_OffsetCategory_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOffsetOptionsByCategory(to_candid_OffsetCategory_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listChallenges(): Promise<Array<Challenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChallenges();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChallenges();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOffsetOptions(): Promise<Array<OffsetOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOffsetOptions();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOffsetOptions();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async simulatePurchase(arg0: OffsetOptionId, arg1: bigint): Promise<OffsetPurchase | null> {
        if (this.processError) {
            try {
                const result = await this.actor.simulatePurchase(arg0, arg1);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.simulatePurchase(arg0, arg1);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ChallengeStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChallengeStatus): ChallengeStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Challenge_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Challenge): Challenge {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ConversionFactor_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversionFactor): ConversionFactor {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_FootprintEstimate_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FootprintEstimate): FootprintEstimate {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_OffsetCategory_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OffsetCategory): OffsetCategory {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_OffsetOption_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OffsetOption): OffsetOption {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProgress_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProgress): UserProgress {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Challenge]): Challenge | null {
    return value.length === 0 ? null : from_candid_Challenge_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OffsetOption]): OffsetOption | null {
    return value.length === 0 ? null : from_candid_OffsetOption_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OffsetPurchase]): OffsetPurchase | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ChallengeId;
    durationDays: bigint;
    status: _ChallengeStatus;
    title: string;
    co2ReductionKg: number;
    description: string;
    participantCount: bigint;
    category: string;
}): {
    id: ChallengeId;
    durationDays: bigint;
    status: ChallengeStatus;
    title: string;
    co2ReductionKg: number;
    description: string;
    participantCount: bigint;
    category: string;
} {
    return {
        id: value.id,
        durationDays: value.durationDays,
        status: from_candid_ChallengeStatus_n17(_uploadFile, _downloadFile, value.status),
        title: value.title,
        co2ReductionKg: value.co2ReductionKg,
        description: value.description,
        participantCount: value.participantCount,
        category: value.category
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unit: string;
    moneySavedPerUnit: number;
    category: _Category;
    co2KgPerUnit: number;
}): {
    unit: string;
    moneySavedPerUnit: number;
    category: Category;
    co2KgPerUnit: number;
} {
    return {
        unit: value.unit,
        moneySavedPerUnit: value.moneySavedPerUnit,
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        co2KgPerUnit: value.co2KgPerUnit
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    daysCompleted: bigint;
    challengeId: _ChallengeId;
    lastCheckIn: [] | [bigint];
    currentStreak: bigint;
}): {
    daysCompleted: bigint;
    challengeId: ChallengeId;
    lastCheckIn?: bigint;
    currentStreak: bigint;
} {
    return {
        daysCompleted: value.daysCompleted,
        challengeId: value.challengeId,
        lastCheckIn: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.lastCheckIn)),
        currentStreak: value.currentStreak
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OffsetOptionId;
    name: string;
    description: string;
    category: _OffsetCategory;
    iconUrl: string;
    co2OffsetKg: number;
    costUsd: number;
}): {
    id: OffsetOptionId;
    name: string;
    description: string;
    category: OffsetCategory;
    iconUrl: string;
    co2OffsetKg: number;
    costUsd: number;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        category: from_candid_OffsetCategory_n31(_uploadFile, _downloadFile, value.category),
        iconUrl: value.iconUrl,
        co2OffsetKg: value.co2OffsetKg,
        costUsd: value.costUsd
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moneySavedPerYear: number;
    category: _Category;
    co2KgPerYear: number;
}): {
    moneySavedPerYear: number;
    category: Category;
    co2KgPerYear: number;
} {
    return {
        moneySavedPerYear: value.moneySavedPerYear,
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        co2KgPerYear: value.co2KgPerYear
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transportation: null;
} | {
    diet: null;
} | {
    homeEnergy: null;
} | {
    shopping: null;
}): Category {
    return "transportation" in value ? Category.transportation : "diet" in value ? Category.diet : "homeEnergy" in value ? Category.homeEnergy : "shopping" in value ? Category.shopping : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    upcoming: null;
} | {
    completed: null;
}): ChallengeStatus {
    return "active" in value ? ChallengeStatus.active : "upcoming" in value ? ChallengeStatus.upcoming : "completed" in value ? ChallengeStatus.completed : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    treePlanting: null;
} | {
    oceanCleanup: null;
} | {
    communitySolar: null;
} | {
    wildlifeConservation: null;
}): OffsetCategory {
    return "treePlanting" in value ? OffsetCategory.treePlanting : "oceanCleanup" in value ? OffsetCategory.oceanCleanup : "communitySolar" in value ? OffsetCategory.communitySolar : "wildlifeConservation" in value ? OffsetCategory.wildlifeConservation : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Challenge>): Array<Challenge> {
    return value.map((x)=>from_candid_Challenge_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConversionFactor>): Array<ConversionFactor> {
    return value.map((x)=>from_candid_ConversionFactor_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OffsetOption>): Array<OffsetOption> {
    return value.map((x)=>from_candid_OffsetOption_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FootprintEstimate>): Array<FootprintEstimate> {
    return value.map((x)=>from_candid_FootprintEstimate_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_ChallengeStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChallengeStatus): _ChallengeStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_FootprintEstimate_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FootprintEstimate): _FootprintEstimate {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_FootprintInput_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FootprintInput): _FootprintInput {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_OffsetCategory_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OffsetCategory): _OffsetCategory {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moneySavedPerYear: number;
    category: Category;
    co2KgPerYear: number;
}): {
    moneySavedPerYear: number;
    category: _Category;
    co2KgPerYear: number;
} {
    return {
        moneySavedPerYear: value.moneySavedPerYear,
        category: to_candid_Category_n4(_uploadFile, _downloadFile, value.category),
        co2KgPerYear: value.co2KgPerYear
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: number;
    unit: string;
    category: Category;
}): {
    value: number;
    unit: string;
    category: _Category;
} {
    return {
        value: value.value,
        unit: value.unit,
        category: to_candid_Category_n4(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChallengeStatus): {
    active: null;
} | {
    upcoming: null;
} | {
    completed: null;
} {
    return value == ChallengeStatus.active ? {
        active: null
    } : value == ChallengeStatus.upcoming ? {
        upcoming: null
    } : value == ChallengeStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OffsetCategory): {
    treePlanting: null;
} | {
    oceanCleanup: null;
} | {
    communitySolar: null;
} | {
    wildlifeConservation: null;
} {
    return value == OffsetCategory.treePlanting ? {
        treePlanting: null
    } : value == OffsetCategory.oceanCleanup ? {
        oceanCleanup: null
    } : value == OffsetCategory.communitySolar ? {
        communitySolar: null
    } : value == OffsetCategory.wildlifeConservation ? {
        wildlifeConservation: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    transportation: null;
} | {
    diet: null;
} | {
    homeEnergy: null;
} | {
    shopping: null;
} {
    return value == Category.transportation ? {
        transportation: null
    } : value == Category.diet ? {
        diet: null
    } : value == Category.homeEnergy ? {
        homeEnergy: null
    } : value == Category.shopping ? {
        shopping: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FootprintInput>): Array<_FootprintInput> {
    return value.map((x)=>to_candid_FootprintInput_n2(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FootprintEstimate>): Array<_FootprintEstimate> {
    return value.map((x)=>to_candid_FootprintEstimate_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
